### ISSUE TITLE
[Usage] Issues related to installing or running AIOS

### ISSUE THREAD

**Issue by evison** [agiresearch/AIOS#214]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Your current environment

This thread is dedicated to gathering any challenges, obstacles, or errors encountered during the installation or use of AIOS, particularly from those new to the platform. If you run into any issues, whether it's a bug, an inconvenience, or something else during the setup or operation of AIOS, please share them here. Our team will work to optimize AIOS based on your feedback.

### How would you like to use aios

I want to run aios with the llm endpoint: xxx for agent: xxx.

**Comment by deepak-pradhan** [comment]
I could installed successfully this evening

**Comment by deepak-pradhan** [comment]
AIOS installation on Android phone (arm64/Snapdragon 8 gen2) using Termux.

TEST result from last weekend:

1. All requirements were met, with little prep on Termux. 
Pandas and Polars required termux tur repo.

2. Only issue is with torch, it requires ANDROID_NDK to build/install. This weekend will install NDK and retry.![Screenshot_20240901_155312_Termux.jpg](https://github.com/user-attachments/assets/b6f20a07-1f27-4da5-bcf1-eb4818771a28)

**Comment by worstkid92** [comment]
Hi,professor,I followed the installation process and succeed. But for use,I use ollama as backend. I ran 
`$ python main.py --llm_name ollama/llama3:8b --use_backend ollama # use ollama/llama3:8b for example` after installation. And it showed
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/codes/AIOS/AIOS/main.py", line 118, in <module>
    main()
  File "/mnt/codes/AIOS/AIOS/main.py", line 110, in main
    awaitAgentExecution(agent_id)
  File "/mnt/codes/AIOS/AIOS/aios/hooks/llm.py", line 107, in awaitAgentExecution
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/codes/AIOS/AIOS/pyopenagi/agents/agent_factory.py", line 83, in run_agent
    agent = self.activate_agent(
            ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/codes/AIOS/AIOS/pyopenagi/agents/agent_factory.py", line 61, in activate_agent
    self.manager.download_agent(
  File "/mnt/codes/AIOS/AIOS/pyopenagi/manager/manager.py", line 67, in download_agent
    response = requests.get(f"{self.base_url}/api/download", params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/download?author=example&name=academic_agent (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbf01d80610>: Failed to establish a new connection: [Errno 111] Connection refused'))`

May I ASK WHAT DID I MISS?
