### ISSUE TITLE
[Usage] Follow Quickstart but failed in  HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/download?author=example&name=academic_agent

### ISSUE THREAD

**Issue by worstkid92** [agiresearch/AIOS#242]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Your current environment

Ubuntu22,Using conda with python3.11
GPU v100

### How would you like to use aios

I want to run aios with the Ollama llm endpoint
All the steps I used:
`pip install -r requirements-cuda.txt
`
`python main.py --llm_name ollama/llama3.1 --use_backend ollama --max_gpu_memory '{"0": "24GB"}' --eval_device "cuda:0" --max_new_tokens 256
`
But got traceback:
```
  warnings.warn(
Main ID is: 1097012
[🤖ollama/llama3.1] AIOS has been successfully initialized.

Traceback (most recent call last):
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/http/client.py", line 996, in send
    self.connect()
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa587f6aa10>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/download?author=example&name=academic_agent (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa587f6aa10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/codes/AIOS/AIOS/main.py", line 118, in <module>
    main()
  File "/mnt/codes/AIOS/AIOS/main.py", line 110, in main
    awaitAgentExecution(agent_id)
  File "/mnt/codes/AIOS/AIOS/aios/hooks/llm.py", line 107, in awaitAgentExecution
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/codes/AIOS/AIOS/pyopenagi/agents/agent_factory.py", line 83, in run_agent
    agent = self.activate_agent(
            ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/codes/AIOS/AIOS/pyopenagi/agents/agent_factory.py", line 61, in activate_agent
    self.manager.download_agent(
  File "/mnt/codes/AIOS/AIOS/pyopenagi/manager/manager.py", line 67, in download_agent
    response = requests.get(f"{self.base_url}/api/download", params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/anaconda3_install/envs/venv/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/download?author=example&name=academic_agent (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa587f6aa10>: Failed to establish a new connection: [Errno 111] Connection refused'))


```

What did I miss. I saw port 3000 is for webui from source code?

**Comment by dongyuanjushi** [comment]
It is because the current agentmanager has some issues connecting to the vercel server and we are fixing that. We have temporarily reverted the code to the latest stable version to fix this for now.
