### ISSUE TITLE
[Usage] 

### ISSUE THREAD

**Issue by luyhcsu** [agiresearch/AIOS#280]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Your current environment

(llm) liang@pc01:~/hpc/AIOS$ python main.py --llm_name ollama/llama3:8b --use_backend ollama --max_gpu_memory '{"0": "24GB"}' --eval_device "cuda:0" --max_new_tokens 1024
Main ID is: 302837
[🤖ollama/llama3:8b] AIOS has been successfully initialized.

Using latest cached version of example/academic_agent (v0.0.1)
agenthub.cache.example.academic_agent.0-0-1.agent
[example/academic_agent/0.0.1] Tell me what is the prollm paper mainly about

[Scheduler] example/academic_agent/0.0.1 is executing. 

[🤖ollama/llama3:8b] example/academic_agent/0.0.1 is switched to executing.

llama3:8b
***** original result: Here's a plan to help you find out what the paper is mainly about:

[{"action_type": "call_tool", "action": "Query papers or topics in arxiv to get relevant results. ", "tool_use": ["arxiv"]},
{"action_type": "analyze_results", "action": "Analyze the query results and identify the most relevant papers. ", "tool_use": []}]

Please provide me with more information about the paper you're interested in, such as its title or authors (if known), and I'll help you generate a plan to find out what it's mainly about! *****
[Scheduler] Current request of example/academic_agent/0.0.1 is done. Thread ID is 302879

Traceback (most recent call last):
  File "/home/liang/hpc/AIOS/main.py", line 93, in <module>
    main()
  File "/home/liang/hpc/AIOS/main.py", line 87, in main
    await_agent_execution(agent_id)
  File "/home/liang/hpc/AIOS/aios/hooks/llm.py", line 109, in awaitAgentExecution
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/liang/hpc/AIOS/pyopenagi/agents/agent_factory.py", line 93, in run_agent
    output = agent.run()
  File "/home/liang/hpc/AIOS/agenthub/cache/example/academic_agent/0-0-1/agent.py", line 230, in run
    workflow = self.automatic_workflow()
  File "/home/liang/hpc/AIOS/agenthub/cache/example/academic_agent/0-0-1/agent.py", line 163, in automatic_workflow
    workflow = self.check_workflow(response.response_message)
AttributeError: 'NoneType' object has no attribute 'response_message'

### How would you like to use aios

I want to run aios with the llm endpoint: xxx for agent: xxx.

**Comment by evison** [comment]
Thank you for the issue, can you clarify what base operating system you are using, such as mac/linux/windows, etc., what is the version of the base os, and the version of ollama you are using? Thanks.

**Comment by luyhcsu** [comment]
> Thank you for the issue, can you clarify what base operating system you are using, such as mac/linux/windows, etc., what is the version of the base os, and the version of ollama you are using? Thanks.

Environment:
OS: ubuntu 22.04
Python: 3.10
AIOS Version: Latest
LLM: llama3:8b
ollama:0.3.9

**Comment by dongyuanjushi** [comment]
> > Thank you for the issue, can you clarify what base operating system you are using, such as mac/linux/windows, etc., what is the version of the base os, and the version of ollama you are using? Thanks.
> 
> Environment: OS: ubuntu 22.04 Python: 3.10 AIOS Version: Latest LLM: llama3:8b ollama:0.3.9

Thank you for raising this issue. I will follow up and check this.
