### ISSUE TITLE
[Bug] TypeError when using GPT-3.5-turbo model

### ISSUE THREAD

**Issue by XiangZhang-zx** [agiresearch/AIOS#340]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Describe the bug

Description:
Running main.py with gpt-3.5-turbo results in the following error:
TypeError: 'NoneType' object is not iterable
However, running with gemini-1.5-flash works fine.

Steps to Reproduce:

Set OpenAI API key:
export OPENAI_API_KEY=<YOUR_OPENAI_API_KEY>

Run the script:
python main.py --llm_name gpt-3.5-turbo

Error Traceback:
Traceback (most recent call last):
File ".../aios/scheduler/fifo_scheduler.py", line 135, in run_tool_syscall
response = self.tool_manager.address_request(tool_syscall)
File ".../aios/tool/manager.py", line 14, in address_request
for tool_call in tool_calls:
TypeError: 'NoneType' object is not iterable

<img width="581" alt="Screenshot 2024-11-21 at 2 49 38 PM" src="https://github.com/user-attachments/assets/f51988e2-ea9d-4bd9-a474-4ac1544c7bb9">

**Comment by XiangZhang-zx** [comment]
This issue was specific to version 0.1.0 and has been resolved in version 0.2.0. Closing this issue to keep the repository clean.
