### ISSUE TITLE
[Bug] Packages installation from requirements.txt is failing in python virtual env 3.12.3

### ISSUE THREAD

**Issue by tusharanand29** [agiresearch/AIOS#344]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I am sure the issue hasn't been already addressed by searching through https://github.com/agiresearch/AIOS/issues.
- [X] The usage issue is not resolved by updating to the latest stable version in the main branch.

### Describe your current environment

Kernel : 6.8.0-48-generic
OS: Ubuntu 24.04.1 LTS
GPU: Not present
Python virtual env version: 3.12.3

### Describe the bug

Packages installation from requirements.txt is failing in python virtual env 3.12.3
`$ pip install -r requirements.txt
Collecting google-generativeai (from -r requirements.txt (line 1))
  Using cached google_generativeai-0.8.3-py3-none-any.whl.metadata (3.9 kB)
Collecting openai==1.20.0 (from -r requirements.txt (line 2))
  Using cached openai-1.20.0-py3-none-any.whl.metadata (21 kB)
Collecting pandas==2.2.2 (from -r requirements.txt (line 3))
  Using cached pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting protobuf==4.25.3 (from -r requirements.txt (line 4))
  Using cached protobuf-4.25.3-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Collecting pydantic==2.7.0 (from -r requirements.txt (line 5))
  Using cached pydantic-2.7.0-py3-none-any.whl.metadata (103 kB)
Collecting Pympler==1.0.1 (from -r requirements.txt (line 6))
  Using cached Pympler-1.0.1-py3-none-any.whl.metadata (3.4 kB)
Collecting click==8.1.7 (from -r requirements.txt (line 7))
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting ollama (from -r requirements.txt (line 8))
  Using cached ollama-0.4.1-py3-none-any.whl.metadata (4.8 kB)
Collecting fastapi (from -r requirements.txt (line 9))
  Using cached fastapi-0.115.5-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn (from -r requirements.txt (line 10))
  Using cached uvicorn-0.32.1-py3-none-any.whl.metadata (6.6 kB)
Collecting torch (from -r requirements.txt (line 11))
  Using cached torch-2.5.1-cp312-cp312-manylinux1_x86_64.whl.metadata (28 kB)
Collecting transformers (from -r requirements.txt (line 12))
  Using cached transformers-4.46.3-py3-none-any.whl.metadata (44 kB)
Collecting accelerate (from -r requirements.txt (line 13))
  Using cached accelerate-1.1.1-py3-none-any.whl.metadata (19 kB)
Collecting anthropic (from -r requirements.txt (line 14))
  Using cached anthropic-0.39.0-py3-none-any.whl.metadata (22 kB)
Collecting python-dotenv (from -r requirements.txt (line 15))
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting litellm (from -r requirements.txt (line 16))
  Using cached litellm-1.52.16-py3-none-any.whl.metadata (33 kB)
Collecting pyfzf (from -r requirements.txt (line 17))
  Using cached pyfzf-0.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting npm (from -r requirements.txt (line 18))
  Using cached npm-0.1.1.tar.gz (2.5 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting platformdirs (from -r requirements.txt (line 19))
  Using cached platformdirs-4.3.6-py3-none-any.whl.metadata (11 kB)
Collecting arxiv (from -r requirements.txt (line 20))
  Using cached arxiv-2.1.3-py3-none-any.whl.metadata (6.1 kB)
Collecting llama-index-embeddings-huggingface (from -r requirements.txt (line 21))
  Using cached llama_index_embeddings_huggingface-0.4.0-py3-none-any.whl.metadata (767 bytes)
Collecting watchdog (from -r requirements.txt (line 22))
  Using cached watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl.metadata (44 kB)
Collecting chromadb (from -r requirements.txt (line 23))
  Using cached chromadb-0.5.20-py3-none-any.whl.metadata (6.8 kB)
Collecting llama_index==0.10.19 (from -r requirements.txt (line 24))
  Using cached llama_index-0.10.19-py3-none-any.whl.metadata (8.8 kB)
Collecting llama_index_core==0.10.19 (from -r requirements.txt (line 25))
  Using cached llama_index_core-0.10.19-py3-none-any.whl.metadata (3.6 kB)
Collecting numpy==1.24.3 (from -r requirements.txt (line 26))
  Using cached numpy-1.24.3.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/user/aios/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 182, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
    super().__init__(
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 54, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 124, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 101, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 745, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/aios/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/user/aios/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/tmp/pip-build-env-djkvy2gz/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'
`

**Comment by dongyuanjushi** [comment]
Thanks for raising this issue. The team also finds that only py3.10 and py3.11 can be installed.

**Comment by dongyuanjushi** [comment]
And the ongoing v0.2.0 version will also update this in the docs.

**Comment by tusharanand29** [comment]
> Thanks for raising this issue. The team also finds that only py3.10 and py3.11 can be installed.

Sure, no problem.
