### ISSUE TITLE
 No module named 'pympler'

### ISSUE THREAD

**Issue by ShangwenWang** [agiresearch/AIOS#39]
Hi,

I tried to run the demo in the README file but got an exception. 

The command and output are:

 python main.py --llm_name gemma-2b-it --max_gpu_memory '{"0": "24GB"}' --eval_device "cuda:0" --max_new_tokens 256
Traceback (most recent call last):
  File "/root/autodl-tmp/AIOS/main.py", line 21, in <module>
    from src.agents.agent_factory import AgentFactory
  File "/root/autodl-tmp/AIOS/src/agents/agent_factory.py", line 14, in <module>
    from pympler import asizeof
ModuleNotFoundError: No module named 'pympler'

Does it mean the file pympler.py is not included in the released code now?

**Comment by ShangwenWang** [comment]
Ok. I resolved this question now but met another one.

pleaseTraceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

Does it mean I cannot connect to Hugging Face? If so, how to address this.

**Comment by dongyuanjushi** [comment]
Pympler dependencies have been added into the requirements.txt. And about the error of connecting to huggingface, I am not sure whether you apply for the access to use the specific model in the huggingface model card.

**Comment by ShangwenWang** [comment]
Thanks for the clarification. I checked that my server cannot ping huggingface. 

I wonder is there any screenshot to show the execution result of AIOS?
