### ISSUE TITLE
ModuleNotFoundError: No module named 'src.tools.bing_search'

### ISSUE THREAD

**Issue by chenggangqcg** [agiresearch/AIOS#6]
python main.py --llm_name gemma-2b-it --max_gpu_memory '{"0": "24GB"}' --eval_device "cuda:0" --max_new_tokens 256

Traceback (most recent call last):
  File "/Users/doudou/project/AIOS/main.py", line 31, in <module>
    from src.agents.travel_agent.travel_agent import TravelAgent
  File "/Users/doudou/project/AIOS/src/agents/travel_agent/travel_agent.py", line 21, in <module>
    from src.tools.bing_search import BingSearch
ModuleNotFoundError: No module named 'src.tools.bing_search'

**Comment by dongyuanjushi** [comment]
The error is fixed, please refer to the latest version.

**Comment by chenggangqcg** [comment]
2024-03-29 08:11:31,036 - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-03-29 08:11:41,047 - DEBUG - Starting new HTTPS connection (2): huggingface.co:443

**Comment by ShangwenWang** [comment]
Hi @chenggangqcg 

I met the same problem. Did you resolve it? Any thought about what to do next?
